# Generated by Django 3.0.3 on 2020-02-18 19:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FacilitiesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedApartment',
            new_name='Apartment',
        ),
    ]
