# Generated by Django 3.0.3 on 2020-03-13 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FacilitiesApp', '0002_auto_20200218_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='date_last_save',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
