# Generated by Django 3.0.3 on 2020-03-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesApp', '0003_auto_20200313_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='username_last_save',
            field=models.CharField(default='n', max_length=100),
            preserve_default=False,
        ),
    ]
