# Generated by Django 3.0.3 on 2020-03-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesApp', '0004_apartment_username_last_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='username_last_save',
            new_name='username_first',
        ),
    ]
