# Generated by Django 3.0.3 on 2020-03-20 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FacilitiesApp', '0005_auto_20200313_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('house_company', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('repair_state', models.CharField(max_length=100)),
                ('repair', models.CharField(max_length=100)),
                ('date_repair', models.DateTimeField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_lastsave', models.DateTimeField(auto_now=True)),
                ('username_first', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
