# Generated by Django 3.0.3 on 2020-03-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesApp', '0006_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='date_lastsave',
            new_name='date_last_save',
        ),
    ]
