# Generated by Django 3.0.3 on 2020-03-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesApp', '0009_auto_20200327_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='received',
            field=models.BooleanField(default='False'),
        ),
    ]
