# Generated by Django 3.0.3 on 2020-03-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesApp', '0010_ticket_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fault',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='repair',
            field=models.TextField(blank=True),
        ),
    ]
