# Generated by Django 3.0.3 on 2020-03-27 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesApp', '0011_auto_20200327_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_repair',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
