# Generated by Django 3.0.3 on 2020-03-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesApp', '0014_auto_20200327_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fault',
            field=models.TextField(),
        ),
    ]
