# Generated by Django 3.0.3 on 2020-04-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesApp', '0017_auto_20200331_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='repair_state',
            field=models.IntegerField(default=0),
        ),
    ]
