# Generated by Django 3.0.3 on 2020-04-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesApp', '0018_auto_20200416_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='received',
        ),
    ]
