# Generated by Django 3.0.3 on 2020-04-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesApp', '0019_remove_ticket_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='repair_state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
