# Generated by Django 3.0.3 on 2020-04-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesApp', '0020_auto_20200423_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='repair_state',
            field=models.CharField(max_length=100),
        ),
    ]
