# Generated by Django 3.0.3 on 2020-05-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesApp', '0021_auto_20200423_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_repair',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
