# Generated by Django 3.0.3 on 2020-05-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesApp', '0024_auto_20200521_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_repair',
            field=models.DateTimeField(null=True),
        ),
    ]
