# Generated by Django 3.0.3 on 2020-05-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesApp', '0025_auto_20200521_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_repair',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
