# Generated by Django 3.0.3 on 2020-05-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacilitiesApp', '0028_auto_20200521_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_repair',
            field=models.DateField(blank=True, null=True),
        ),
    ]
